cameraclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path, include
from .views import *
from .utils import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('members', MemberListView.as_view(), name='members'),
    path('members/add', add_member, name='add_member'),
    path('', MainGalleryView.as_view(), name = 'main-gallery'),
    path('aboutus', AboutUsView.as_view(), name='aboutus'),
    path('newsletters/<int:year>/', NewslettersView.as_view(), name='news'),
    path('newsletters/add/', NewsletterCreateView.as_view(), name='add_newsletter'),
    path('newsletters/edit/<int:pk>/', NewsletterUpdateView.as_view(), name='edit_newsletter'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('events/<int:year>/', EventsView.as_view(), name='events'),
    path('events/<int:year>/#today_bookmark', EventsView.as_view(), name='events_now'),
    path('events/', EventsView.as_view(), name='events'),
    path('event/<int:pk>', EventDetailView.as_view(), name='event'),
    path('event/<int:pk>/AddFile', UploadEventFileView.as_view(), name='event_add_file'),
    path('gallery/<int:gallery_pk>/zip', zip_gallery, name='gallery-zip'),
    path('gallery/<int:in_gallery_pk>/transfer', copy_to_gallery, name='copy_to_gallery'),
    path('create_events', createwaccevents, name='create-events'),
    path('move_events', move_imported_events, name='move-events'),
    path('1st_events', move_comps_to_1st, name='1st-events'),
    path('import_pics', import_pics, name='import_pics'),
    path('cleanup_photos', cleanup_photos, name='cleanup_photos'),
    path('set_comp_images', set_comp_images, name='set_comp_images'),
    path('event/<int:event_id>/create_comp', CompCreateView.as_view(), name='create_comp'),
    path('event/<int:event_id>/create_compnight', setup_competition_night, name='create_compnight'),
    path('event/<int:pk>/create_gallery', GalleryCreateView.as_view(), name='gallery_create'),
    path('event/<int:event_id>/judge_notes/', JudgeNotesView.as_view(), name='judge_notes'),
    path('event/<int:pk>/slideshow/', AllCompsSlideshow.as_view(), name='all_slideshow'),
    path('competitions/<int:comp_pk>/award_gold_dist/<image_pk>', award_gold_dist, name='award_gold_dist'),
    path('competitions/<int:comp_pk>/award_gold/<image_pk>', award_gold, name='award_gold'),
    path('competitions/<int:comp_pk>/award_silver/<image_pk>', award_silver, name='award_silver'),
    path('competitions/<int:comp_pk>/award_bronze/<image_pk>', award_bronze, name='award_bronze'),
    path('competitions/<int:comp_pk>/award_merit/<image_pk>', award_merit, name='award_merit'),
    path('competitions/<int:pk>/enter/', EnterCompetitionView.as_view(), name='enter_competition'),
    path('competitions/<int:comp_id>/remove/<int:img_id>', remove_entry, name='remove_entry'),
    path('competitions/<int:competition_id>/vote/', MemberVotingView.as_view(), name='competition_vote'),
    path('competitions/<int:competition_id>/view/', ViewEntriesView.as_view(), name='view_entries'),
    path('competitions/<int:competition_id>/list/', ListEntriesView.as_view(), name='list_entries'),
    path('competitions/<int:competition_id>/count/', count_up_votes, name='count_votes'),
    path('competitions/<int:pk>/addimages/', AddImagesToCompetitionView.as_view(), name='competition_add_images'),
    path('competitions/<int:pk>/edit_prints/', PrintImageBulkEditView.as_view(), name='competition_edit_prints'),
#    path('competitions/<int:pk>/judge/', JudgeJudgingView.as_view(), name='competition_judge'),
    path('competitions/<int:pk>/awards/', CompAwardsView.as_view(), name='competition_awards'),
    path('competitions/<int:year>/totals/', AnnualTotalsView.as_view(), name='totals'),
    path('competitions/night/' , CompNightView.as_view(), name='compnight'),
    path('competitions/<int:pk>/slideshow/', CompNightImagesView.as_view(), name='slideshow'),
    path('competitions/<int:pk>/judge_slideshow/', CompNightJudgesView.as_view(), name='judge_slideshow'),
    path('competitions/<int:pk>/edit_judge_awards/', JudgeAwardUpdateView.as_view(), name='edit_judge_awards'),
    path('competitions/<int:pk>/edit_member_awards/', MemberAwardUpdateView.as_view(), name='edit_member_awards'),
    path('competitions/<int:comp_pk>/create_zip', zip_comp_images, name='create_zip'),
    path('competitions/print_voting', PrintVotingView.as_view(), name='print_voting'),
    path('competitions/print_paper_voting', PrintPaperVotingView.as_view(), name='print_paper_voting'),
    path('competitions/<int:competition_id>/printvotetally/', print_vote_tally_view, name='printvotetally'),
    path('images/<int:pk>/addphoto', UploadPhotoView.as_view(), name='upload_photo'),
    path('add-to-gallery/<int:pk>', AddToGalleryView.as_view(), name='add_to_gallery'),
#    path('end-of-year-entry/', EndOfYearEntryView.as_view(), name='end_of_year_entry'),
    path('end-of-year-entry/mono', eoy_competition, name='end_of_year_entry_mono'),
    path('end-of-year-entry/colour', eoy_competition, name='end_of_year_entry_colour'),
    path('end-of-year-entry/mono_prints', eoy_competition_prints, name='end_of_year_entry_mono_prints'),
    path('end-of-year-entry/colour_prints', eoy_competition_prints, name='end_of_year_entry_colour_prints'),
    path('end-of-year-entry/mono_labels', eoy_competition_labels, name='end_of_year_entry_mono_labels'),
    path('end-of-year-entry/colour_labels', eoy_competition_labels, name='end_of_year_entry_colour_labels'),
    path('resources', ResourcesView.as_view(), name="resources"),
    path('resources/<int:resource_id>/', download_resource, name='download_resource'),
    path("ajax/image-search/", image_search, name="image_search"),
#    path('image', views.image, name='image')
]
 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

main/models.py
import os
from django.core.exceptions import ValidationError
from datetime import timedelta, datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.core.files.storage import default_storage
from django.conf import settings
from tinymce.models import HTMLField
from django.db.models import ImageField
from django.dispatch import receiver
from pdf2image import convert_from_path
from PIL import Image

# Create your models here.

class Blurb(models.Model):
    '''TextFields to be displayed on information pages on the website'''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    contents = HTMLField()
    
    def __str__(self):
        return self.name

def generate_thumbnail(pdf_path, thumb_path, size=(200, 300)):
    # Convert the first page of the PDF file to an image
    images = convert_from_path(pdf_path)
    if images:
        first_page_image = images[0]
        # Resize the image
        resized_image = first_page_image.resize(size)
        # Save the resized image as a thumbnail
        resized_image.save(thumb_path, 'PNG')

class Newsletter(models.Model):
    '''Club Newsletters (issued monthly)'''
    id = models.AutoField(primary_key=True)
    issue_date = models.DateTimeField(default=timezone.now)
    file = models.FileField(upload_to='files/news/')
    thumb = models.ImageField(upload_to='files/news/thum', blank=True, null=True)
    
    def __str__(self):
        return "Newsletter: " + self.issue_date.strftime("%d/%m/%Y")

@receiver(models.signals.post_save, sender=Newsletter)
def make_thumbnail(sender, instance, **kwargs):
    if instance.thumb:
        return
    if instance.file:
        pdf_path = instance.file.path
        thumb_path = os.path.join(os.path.dirname(pdf_path), 'thumbnails', f"{instance.id}.png")
        generate_thumbnail(pdf_path, thumb_path)
        instance.thumb = os.path.relpath(thumb_path, settings.MEDIA_ROOT)
        instance.save(update_fields=['thumb'])

class Person(models.Model):
    '''The person model that contains contact details for a person.
    A Person can be a Member or a Judge (or neither).
    A Person can be a User or not.'''
    id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    mobile = models.CharField(max_length=50, null=True, blank=True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.PROTECT)
    
    def __str__(self):
        return self.firstname + " " + self.surname
    
    def listname(self):
        return self.surname + ', ' + self.firstname
    
    class Meta:
        ordering = ["firstname", "surname"]
    
class Member(models.Model):
    '''The member model that contains present and past members.
    Images belong to Members.'''
    id = models.AutoField(primary_key=True)
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    joined = models.DateField(null=True, blank=True)
    current = models.BooleanField(default=True)
    
    def __str__(self):
        return self.person.firstname + " " + self.person.surname
    
    class Meta:
        ordering = ["person__firstname"]
    
class Payment(models.Model):
    '''money paid by a member, for use by the Treasurer'''
    id = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    paid_for = models.CharField(max_length=150) 

class Position(models.Model):
    '''Positions on the Committee, used to create Contacts list'''
    id = models.AutoField(primary_key=True)
    position = models.CharField(max_length=50)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='position')
    order = models.SmallIntegerField()
    
    def __str__(self):
        return self.position
    
    class Meta:
        ordering = ["order"]
    
class Judge(models.Model):
    '''The Judge model that contains present and past judges.'''
    id = models.AutoField(primary_key=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='judge')
    current = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.person.firstname + " " + self.person.surname
    
class Image(models.Model):
    '''Images entered into competitions or uploaded to galleries,
    may have no image file if it was a print competition entry with no subsequent upload.'''
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Person, on_delete=models.PROTECT)
    print = models.BooleanField(default=False, verbose_name="Entered as a print")
    photo = models.ImageField(upload_to='photos/', null=True, blank=True)
    
    def __str__(self):
        return self.title + ": " + self.author.firstname + " " + self.author.surname

    class Meta:
        ordering = ["title", "author", "print"]

def file_cleanup(sender, **kwargs):
    """
    Remove the jpg when removing an Image object from the database
    Prevents buildup of orphaned images

    Copied from https://timonweb.com/django/cleanup-files-and-images-on-model-delete-in-django/
    just changed to assign 'photo' as the field name
    As not all Image instances have a file I had to add the try before if( hasattr...
    """
    
    fieldname = 'photo'
    try:
        field = sender._meta.get_field(fieldname)
    except:
        field = None

    if field and isinstance(field, ImageField):
        inst = kwargs["instance"]
        f = getattr(inst, fieldname)
        m = inst.__class__._default_manager
        try:
            if (
                hasattr(f, "path")
                and os.path.exists(f.path)
                and not m.filter(
                    **{"%s__exact" % fieldname: getattr(inst, fieldname)}
                ).exclude(pk=inst._get_pk_val())
            ):
                try:
                    default_storage.delete(f.path)
                except:
                    pass
        except:
            pass
   
post_delete.connect(
    file_cleanup, sender=Image, dispatch_uid="gallery.image.file_cleanup"
)

class Event(models.Model):
    '''An Event is anything with a start and end datetime and can include galleries and/or competitions.
    The most common Events are competition nights which will have a number of competitions, workshops and outings,
    these may have non-competition galleries.
    Events can be hidden and only visible to Comp Director, *President & listed in extra_viewers'''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    starts = models.DateTimeField()
    ends = models.DateTimeField()
    file = models.FileField(upload_to='files/', null=True, blank=True)
    image = models.ForeignKey(Image, null=True, blank=True, on_delete=models.CASCADE)
    hide_from_members_until = models.DateTimeField(null=True, blank=True)
    hide_from_public = models.BooleanField(default=False, null=True)
    extra_viewers = models.ManyToManyField(Person, blank=True)
    
    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension
    
    def __str__(self):
        return self.name + " (" + self.starts.strftime("%m/%d/%Y") + ")"
    
    class Meta:
        ordering = ['starts']

class Rule(models.Model):
    '''A Rule is a restriction on a Competition'''
    id = models.AutoField(primary_key=True)
    rule = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.rule
    
    class Meta:
        ordering = ['description']

class Awarder(models.Model):
    id = models.AutoField(primary_key=True)
    awarded_by = models.CharField(max_length=100, blank=True)
    judge = models.BooleanField(default=False)
    members = models.BooleanField(default=True)
    
    def __str__(self):
        return self.awarded_by

class CompetitionType(models.Model):
    '''A Competition is a collection of images for a club Competition'''
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=50)
    rules = models.ManyToManyField(Rule, blank=True)
    active = models.BooleanField(default=True)
    contributes_to_annual = models.BooleanField(default=True)
    selection_not_places = models.BooleanField(default=False) 
    awarders = models.ManyToManyField(Awarder)
    rank = models.PositiveSmallIntegerField(default=0)
    
    def __str__(self):
        return self.type

class Subject(models.Model):
    '''A Subject is the description of the images that may be entered into a Competition.
    There may be mutiple Competitions with the same subject.  For example lots of Open Colour 
    and Open Mono Subject Competitions and Digital and Print Competitions with the same Subject'''
    id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    year = models.SmallIntegerField(null=True)
    
    def __str__(self):
        return self.subject
   
class Competition(models.Model):
    '''A Competition is a collection of images for a club competition and is held at an Event'''
    id = models.AutoField(primary_key=True)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.PROTECT)
    open_for_entries = models.DateTimeField(null=True)
    entries_close = models.DateTimeField(null=True)
    open_for_judging = models.DateTimeField(null=True)
    judging_closes =  models.DateTimeField(null=True)
    judge_awards = models.BooleanField(default=True)
    members_vote = models.BooleanField(default=True)

main/templates/main/base.html
{% load static %}
{% now "Y" as this_year %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>WACC</title>
    {% endblock title %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- CSS (stable release) -->
    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
    <!-- Make sure jQuery comes first -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- JS (stable release) -->
    <script src="{% static 'js/select2.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'admin/js/core.js' %}"></script>
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% now "Y" as this_year %}
      {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'main-gallery' %}">
              <img src="{% static "WACC_icon.png" %}"
                   class="d-inline-block align-text-middle">
            West Australian Camera Club</a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'main-gallery' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'aboutus' %}">About The Club</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'events' this_year %}#today_bookmark">Events Calendar</a>
                </li>
                {% if user.is_authenticated %}
                {% if user.person.member %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'resources' %}">Resources</a>
                </li>
                {% endif %}
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'news' this_year %}">Newsletters</a>
                </li>
                {% if perms.main.change_event %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">Committee Only</a>
                    <ul class="dropdown-menu">
                      <li>
                        <a class="dropdown-item" href="{% url 'compnight' %}">Competition Night</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'totals' this_year %}">Annual Results</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'members' %}">Members</a>
                      </li>
                    </ul>
                  </li>
                {% endif %}
              </ul>
            </div>
            <div class="d-flex">
              {% if user.is_authenticated %}
              {% if user.person.member %}
                <a class="btn btn-outline-primary mx-2 text-nowrap"
                  href="{% url 'profile' user.person.member.id %}">Hi {{ user.person.firstname }}</a>
                  {% if print_voting %}
                  <a class="btn btn-outline-success mx-2 text-nowrap"
                    href="{% url 'print_voting' %}">Print Voting</a>
                  {% endif %}
              {% endif %}
                <a class="btn btn-secondary"
                   href="{% url 'logout' %}">Logout</a>
                {% if user.is_staff %}
                  <a class="btn btn-success ml-1"
                     href="{% url 'admin:index' %}?next={{ request.path }}">Admin</a>
                {% endif %}
              {% else %}
                <a class="btn btn-outline-primary"
                   href="{% url 'login' %}?next={{ request.path }}">Login</a>
              {% endif %}
            </div>
          </div>
        </nav>
      {% endblock navbar %}
    </div>
    {% if messages %}
      <div id="message-container">
        {% for message in messages %}
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
             <div class="alert alert-success alert-dismissible fade show" role="alert">
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
             <div class="alert alert-info alert-dismissible fade show" role="alert">
          {% else %}
             <div class="alert alert-primary alert-dismissible fade show" role="alert">
          {% endif %}
          {{ message }}
            <button type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"></button>
              </div>
        {% endfor %}
      </div>
    {% endif %}
    <main class="flex-grow-1">
      {% block content %}
      {% endblock content %}
    <main>
      <div class="container my-3">
        <div class="d-flex justify-content-center sticky-bottom bg-white pt-1">
          <p class="text-center">
            All images displayed on this site are copyright of WA Camera Club members and may not be
            used for any purpose without prior permission of the photographer in question.
          </p>
        </div>
      </div>
    </div>
</div>

<script src={% static 'js/bootstrap.bundle.min.js' %}></script>
  <script>
    // Auto-dismiss messages after 5 seconds
    document.addEventListener('DOMContentLoaded', function() {
      setTimeout(function() {
          var messageContainer = document.getElementById('message-container');
          if (messageContainer) {
              messageContainer.style.opacity = '0';
              setTimeout(function() {
                  messageContainer.style.display = 'none';
              }, 1000); // Fade out duration
          }
      }, 5000); // Auto-dismiss duration
    });
    // Attach event listener to window for clicks
      window.addEventListener('click', function(event) {
        var target = event.target;

        // close the modal
        var modal = document.querySelector('.modal.show');
        if (modal) {
            var modalInstance = bootstrap.Modal.getInstance(modal);
            if (modalInstance) {
                modalInstance.hide(); // Close the modal
            }
        }
      });
    // Attach event listener to window for contextmenu (right-click) events
    window.addEventListener('contextmenu', function(event) {
      // Prevent the default behavior of the context menu (i.e., block it from opening)
      event.preventDefault();
      // Check if the modal is open
      var modal = document.querySelector('.modal.show');
      if (modal) {
          var modalInstance = bootstrap.Modal.getInstance(modal);
          if (modalInstance) {
              modalInstance.hide(); // Close the modal
          }
      }
    });
  </script>
  <script>
    $(document).ready(function() {
      $('.select2').select2({
          width: '100%',
          placeholder: "Select images...",
      });
    });
  </script>
  {% block scripts %}{% endblock scripts %}
  </body>
</html>

main/templates/main/eoy_labels.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>WACC</title>
    {% endblock title %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'admin/js/core.js' %}"></script>
  </head>
  <body>
    <h1>{{ competition }}</h1>
        <table class="eoy-label">
            {% for image in images %}
            <tr>
                <td>{{ image.title }}</td>
            </tr>
            {% endfor %}
        </table>
    <a class="btn btn-primary" href="{% url 'event' competition.event.id %}" >Back</a>
  </body>
</html>

main/templates/main/gallery_upload_form.html
{% extends "main/base.html" %}

{% block content %}
<div class="container">
    <div class="col-10">
        <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Enter Image for {{ gallery }}</h2>
        
        {% if perms.main.change_competition %}
        <div class="my-4">
          <a class="btn btn-primary btn-block mt-4"
             href="{% url 'add_to_gallery' gallery.id %}">Add Multiple Images to Gallery</a>
        </div>  
        {% endif %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
          <div class="mb-3">
            {% comment %} {% if field.name == 'print' %}
            <label class="form-check-label mr-5">{{ field.label }}</label>
            {% endif %} {% endcomment %}
            {% if field.errors %}
                <div class="form-control is-invalid">
                    {{ field }}
                </div>
                <div id="{{ field.name }}Feedback" class="invalid-feedback">
                    {{ field.errors }}
                </div>
            {% elif field.name == "print" %}
            {% else %}
                {{ field }}
            {% endif %}
            {% if field.name == 'title' %}
            <div id="titleHelp" class="form-text">The title will be auto-capitalised for display.</div>
            {% endif %}
          </div>
        {% endfor %}
        <input class="btn btn-outline-primary" type="submit" value="Submit" />
        <div id="previewArea" class="row mt-1">
          <!-- Image previews will be appended here -->
        </div>
        
        </form>

        
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const fileInput = document.getElementById("fileInput");
    const previewArea = document.getElementById("previewArea");

    fileInput.addEventListener("change", function(event) {
        const files = event.target.files;
        previewArea.innerHTML = ""; // Clear previous previews

        if (files.length === 0) {
            const p = document.createElement("p");
            p.textContent = "No files selected!";
            previewArea.appendChild(p);
            return;
        }

        for (const file of files) {
            if (file && file.type.startsWith("image/")) {
                const reader = new FileReader();
                
                reader.onload = function(e) {
                    const img = document.createElement("img");
                    img.src = e.target.result;
                    img.classList.add("img-thumbnail");
                    img.style.maxWidth = "150px";
                    img.style.marginRight = "10px";
                    
                    const div = document.createElement("div");
                    div.classList.add("col-md-3");
                    div.appendChild(img);

                    previewArea.appendChild(div);
                };

                reader.readAsDataURL(file);
            }
        }
    });
});
</script>
{% endblock scripts %}

main/templates/main/judge_notes.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container-fluid px-0">
        <div>
            {{ blurb|safe }}
        <div>
        <a class="btn btn-primary" href="{% url 'event' event.id %}" >Back</a>
    </div>
{% endblock %}

main/templates/main/member_profile.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    {% now "Y-m-d" as todays_date %}
        <h1>{{ member.person }}</h1>
        <h4>Membership Details</h4>
        <dl class="row">
          <dt class="col-sm-3">Joined Date</dt>
          <dd class="col-sm-9">{{ member.joined }}</dd>
          <dt class="col-sm-3">Current Member</dt>
          <dd class="col-sm-9">{{ member.current }}</dd>
        </dl>
        <h4>Member Details</h4>
        <dl class="row">
          <dt class="col-sm-3">Phone Number</dt>
          <dd class="col-sm-9">{{ member.person.mobile }}</dd>
          <dt class="col-sm-3">Email</dt>
          <dd class="col-sm-9">{{ member.person.user.email }}</dd>
        </dl>
        <div>
        {% if member.person.image_set.all %}
            {% for entries in images.values %}
            <h2>{{ entries.year }}</h2>
            <ul class="image-gallery">
                {% for image in entries.images %}
                    {% include "main/includes/gallery_items.html" %}
                {% endfor %}
            </ul>
            {% endfor %}
        {% endif %}
        </div>
</div>    
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

main/templates/main/membership_list.html
{% extends "main/base.html" %}
{% block content %}
    <div class="container">
        <h1>Committee Members</h1>
        <table class="table">
            {% for user in committee %}
                <tr>
                    {% if user.person.position.all %}
                        <td>
                            {% for pos in user.person.position.all %}
                                {{ pos }}
                            {% endfor %}
                        </div>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>{{ user.person }}</td>
                    <td></td>
                </tr>
            {% endfor %}
        </table>
        <h1 class="mt-5">Current Members</h1>
        <table class="table">
            {% for member in members %}
                {% if member.current %}
                    <tr>
                        <td>{{ member.person }}</td>
                        <td>{{ member.person.user.email }}</td>
                        <td>{{ member.person.mobile }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
        {% if perms.main.change_member %}
            <div class="my-1">
                <a class="btn btn-primary" href="{% url 'add_member' %}">Add New Member</a>
            </div>
        {% endif %}
    </div>
{% endblock content %}