cameraclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path, include
from .views import *
from .utils import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('members', MemberListView.as_view(), name='members'),
    path('members/add', add_member, name='add_member'),
    path('', MainGalleryView.as_view(), name = 'main-gallery'),
    path('aboutus', AboutUsView.as_view(), name='aboutus'),
    path('newsletters/<int:year>/', NewslettersView.as_view(), name='news'),
    path('newsletters/add/', NewsletterCreateView.as_view(), name='add_newsletter'),
    path('newsletters/edit/<int:pk>/', NewsletterUpdateView.as_view(), name='edit_newsletter'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('events/<int:year>/', EventsView.as_view(), name='events'),
    path('events/<int:year>/#today_bookmark', EventsView.as_view(), name='events_now'),
    path('events/', EventsView.as_view(), name='events'),
    path('event/<int:pk>', EventDetailView.as_view(), name='event'),
    path('event/<int:pk>/AddFile', UploadEventFileView.as_view(), name='event_add_file'),
    path('gallery/<int:gallery_pk>/zip', zip_gallery, name='gallery-zip'),
    path('gallery/<int:in_gallery_pk>/transfer', copy_to_gallery, name='copy_to_gallery'),
    path('create_events', createwaccevents, name='create-events'),
    path('move_events', move_imported_events, name='move-events'),
    path('1st_events', move_comps_to_1st, name='1st-events'),
    path('import_pics', import_pics, name='import_pics'),
    path('cleanup_photos', cleanup_photos, name='cleanup_photos'),
    path('set_comp_images', set_comp_images, name='set_comp_images'),
    path('event/<int:event_id>/create_comp', CompCreateView.as_view(), name='create_comp'),
    path('event/<int:event_id>/create_compnight', setup_competition_night, name='create_compnight'),
    path('event/<int:pk>/create_gallery', GalleryCreateView.as_view(), name='gallery_create'),
    path('event/<int:event_id>/judge_notes/', JudgeNotesView.as_view(), name='judge_notes'),
    path('event/<int:pk>/slideshow/', AllCompsSlideshow.as_view(), name='all_slideshow'),
    path('competitions/<int:comp_pk>/award_gold_dist/<image_pk>', award_gold_dist, name='award_gold_dist'),
    path('competitions/<int:comp_pk>/award_gold/<image_pk>', award_gold, name='award_gold'),
    path('competitions/<int:comp_pk>/award_silver/<image_pk>', award_silver, name='award_silver'),
    path('competitions/<int:comp_pk>/award_bronze/<image_pk>', award_bronze, name='award_bronze'),
    path('competitions/<int:comp_pk>/award_merit/<image_pk>', award_merit, name='award_merit'),
    path('competitions/<int:pk>/enter/', EnterCompetitionView.as_view(), name='enter_competition'),
    path('competitions/<int:comp_id>/remove/<int:img_id>', remove_entry, name='remove_entry'),
    path('competitions/<int:competition_id>/vote/', MemberVotingView.as_view(), name='competition_vote'),
    path('competitions/<int:competition_id>/view/', ViewEntriesView.as_view(), name='view_entries'),
    path('competitions/<int:competition_id>/list/', ListEntriesView.as_view(), name='list_entries'),
    path('competitions/<int:competition_id>/count/', count_up_votes, name='count_votes'),
    path('competitions/<int:pk>/addimages/', AddImagesToCompetitionView.as_view(), name='competition_add_images'),
    path('competitions/<int:pk>/edit_prints/', PrintImageBulkEditView.as_view(), name='competition_edit_prints'),
#    path('competitions/<int:pk>/judge/', JudgeJudgingView.as_view(), name='competition_judge'),
    path('competitions/<int:pk>/awards/', CompAwardsView.as_view(), name='competition_awards'),
    path('competitions/<int:year>/totals/', AnnualTotalsView.as_view(), name='totals'),
    path('competitions/night/' , CompNightView.as_view(), name='compnight'),
    path('competitions/<int:pk>/slideshow/', CompNightImagesView.as_view(), name='slideshow'),
    path('competitions/<int:pk>/judge_slideshow/', CompNightJudgesView.as_view(), name='judge_slideshow'),
    path('competitions/<int:pk>/edit_judge_awards/', JudgeAwardUpdateView.as_view(), name='edit_judge_awards'),
    path('competitions/<int:pk>/edit_member_awards/', MemberAwardUpdateView.as_view(), name='edit_member_awards'),
    path('competitions/<int:comp_pk>/create_zip', zip_comp_images, name='create_zip'),
    path('competitions/print_voting', PrintVotingView.as_view(), name='print_voting'),
    path('competitions/print_paper_voting', PrintPaperVotingView.as_view(), name='print_paper_voting'),
    path('competitions/<int:competition_id>/printvotetally/', print_vote_tally_view, name='printvotetally'),
    path('images/<int:pk>/addphoto', UploadPhotoView.as_view(), name='upload_photo'),
    path('add-to-gallery/<int:pk>', AddToGalleryView.as_view(), name='add_to_gallery'),
#    path('end-of-year-entry/', EndOfYearEntryView.as_view(), name='end_of_year_entry'),
    path('end-of-year-entry/mono', eoy_competition, name='end_of_year_entry_mono'),
    path('end-of-year-entry/colour', eoy_competition, name='end_of_year_entry_colour'),
    path('end-of-year-entry/mono_prints', eoy_competition_prints, name='end_of_year_entry_mono_prints'),
    path('end-of-year-entry/colour_prints', eoy_competition_prints, name='end_of_year_entry_colour_prints'),
    path('end-of-year-entry/mono_labels', eoy_competition_labels, name='end_of_year_entry_mono_labels'),
    path('end-of-year-entry/colour_labels', eoy_competition_labels, name='end_of_year_entry_colour_labels'),
    path('resources', ResourcesView.as_view(), name="resources"),
    path('resources/<int:resource_id>/', download_resource, name='download_resource'),
    path("ajax/image-search/", image_search, name="image_search"),
#    path('image', views.image, name='image')
]
 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

main/models.py
import os
from django.core.exceptions import ValidationError
from datetime import timedelta, datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.core.files.storage import default_storage
from django.conf import settings
from tinymce.models import HTMLField
from django.db.models import ImageField
from django.dispatch import receiver
from pdf2image import convert_from_path
from PIL import Image

# Create your models here.

class Blurb(models.Model):
    '''TextFields to be displayed on information pages on the website'''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    contents = HTMLField()
    
    def __str__(self):
        return self.name

def generate_thumbnail(pdf_path, thumb_path, size=(200, 300)):
    # Convert the first page of the PDF file to an image
    images = convert_from_path(pdf_path)
    if images:
        first_page_image = images[0]
        # Resize the image
        resized_image = first_page_image.resize(size)
        # Save the resized image as a thumbnail
        resized_image.save(thumb_path, 'PNG')

class Newsletter(models.Model):
    '''Club Newsletters (issued monthly)'''
    id = models.AutoField(primary_key=True)
    issue_date = models.DateTimeField(default=timezone.now)
    file = models.FileField(upload_to='files/news/')
    thumb = models.ImageField(upload_to='files/news/thum', blank=True, null=True)
    
    def __str__(self):
        return "Newsletter: " + self.issue_date.strftime("%d/%m/%Y")

@receiver(models.signals.post_save, sender=Newsletter)
def make_thumbnail(sender, instance, **kwargs):
    if instance.thumb:
        return
    if instance.file:
        pdf_path = instance.file.path
        thumb_path = os.path.join(os.path.dirname(pdf_path), 'thumbnails', f"{instance.id}.png")
        generate_thumbnail(pdf_path, thumb_path)
        instance.thumb = os.path.relpath(thumb_path, settings.MEDIA_ROOT)
        instance.save(update_fields=['thumb'])

class Person(models.Model):
    '''The person model that contains contact details for a person.
    A Person can be a Member or a Judge (or neither).
    A Person can be a User or not.'''
    id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    mobile = models.CharField(max_length=50, null=True, blank=True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.PROTECT)
    
    def __str__(self):
        return self.firstname + " " + self.surname
    
    def listname(self):
        return self.surname + ', ' + self.firstname
    
    class Meta:
        ordering = ["firstname", "surname"]
    
class Member(models.Model):
    '''The member model that contains present and past members.
    Images belong to Members.'''
    id = models.AutoField(primary_key=True)
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    joined = models.DateField(null=True, blank=True)
    current = models.BooleanField(default=True)
    
    def __str__(self):
        return self.person.firstname + " " + self.person.surname
    
    class Meta:
        ordering = ["person__firstname"]
    
class Payment(models.Model):
    '''money paid by a member, for use by the Treasurer'''
    id = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    paid_for = models.CharField(max_length=150) 

class Position(models.Model):
    '''Positions on the Committee, used to create Contacts list'''
    id = models.AutoField(primary_key=True)
    position = models.CharField(max_length=50)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='position')
    order = models.SmallIntegerField()
    
    def __str__(self):
        return self.position
    
    class Meta:
        ordering = ["order"]
    
class Judge(models.Model):
    '''The Judge model that contains present and past judges.'''
    id = models.AutoField(primary_key=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='judge')
    current = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.person.firstname + " " + self.person.surname
    
class Image(models.Model):
    '''Images entered into competitions or uploaded to galleries,
    may have no image file if it was a print competition entry with no subsequent upload.'''
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Person, on_delete=models.PROTECT)
    print = models.BooleanField(default=False, verbose_name="Entered as a print")
    photo = models.ImageField(upload_to='photos/', null=True, blank=True)
    
    def __str__(self):
        return self.title + ": " + self.author.firstname + " " + self.author.surname

    class Meta:
        ordering = ["title", "author", "print"]

def file_cleanup(sender, **kwargs):
    """
    Remove the jpg when removing an Image object from the database
    Prevents buildup of orphaned images

    Copied from https://timonweb.com/django/cleanup-files-and-images-on-model-delete-in-django/
    just changed to assign 'photo' as the field name
    As not all Image instances have a file I had to add the try before if( hasattr...
    """
    
    fieldname = 'photo'
    try:
        field = sender._meta.get_field(fieldname)
    except:
        field = None

    if field and isinstance(field, ImageField):
        inst = kwargs["instance"]
        f = getattr(inst, fieldname)
        m = inst.__class__._default_manager
        try:
            if (
                hasattr(f, "path")
                and os.path.exists(f.path)
                and not m.filter(
                    **{"%s__exact" % fieldname: getattr(inst, fieldname)}
                ).exclude(pk=inst._get_pk_val())
            ):
                try:
                    default_storage.delete(f.path)
                except:
                    pass
        except:
            pass
   
post_delete.connect(
    file_cleanup, sender=Image, dispatch_uid="gallery.image.file_cleanup"
)

class Event(models.Model):
    '''An Event is anything with a start and end datetime and can include galleries and/or competitions.
    The most common Events are competition nights which will have a number of competitions, workshops and outings,
    these may have non-competition galleries.
    Events can be hidden and only visible to Comp Director, *President & listed in extra_viewers'''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    starts = models.DateTimeField()
    ends = models.DateTimeField()
    file = models.FileField(upload_to='files/', null=True, blank=True)
    image = models.ForeignKey(Image, null=True, blank=True, on_delete=models.CASCADE)
    hide_from_members_until = models.DateTimeField(null=True, blank=True)
    hide_from_public = models.BooleanField(default=False, null=True)
    extra_viewers = models.ManyToManyField(Person, blank=True)
    
    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension
    
    def __str__(self):
        return self.name + " (" + self.starts.strftime("%m/%d/%Y") + ")"
    
    class Meta:
        ordering = ['starts']

class Rule(models.Model):
    '''A Rule is a restriction on a Competition'''
    id = models.AutoField(primary_key=True)
    rule = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.rule
    
    class Meta:
        ordering = ['description']

class Awarder(models.Model):
    id = models.AutoField(primary_key=True)
    awarded_by = models.CharField(max_length=100, blank=True)
    judge = models.BooleanField(default=False)
    members = models.BooleanField(default=True)
    
    def __str__(self):
        return self.awarded_by

class CompetitionType(models.Model):
    '''A Competition is a collection of images for a club Competition'''
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=50)
    rules = models.ManyToManyField(Rule, blank=True)
    active = models.BooleanField(default=True)
    contributes_to_annual = models.BooleanField(default=True)
    selection_not_places = models.BooleanField(default=False) 
    awarders = models.ManyToManyField(Awarder)
    rank = models.PositiveSmallIntegerField(default=0)
    
    def __str__(self):
        return self.type

class Subject(models.Model):
    '''A Subject is the description of the images that may be entered into a Competition.
    There may be mutiple Competitions with the same subject.  For example lots of Open Colour 
    and Open Mono Subject Competitions and Digital and Print Competitions with the same Subject'''
    id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    year = models.SmallIntegerField(null=True)
    
    def __str__(self):
        return self.subject
   
class Competition(models.Model):
    '''A Competition is a collection of images for a club competition and is held at an Event'''
    id = models.AutoField(primary_key=True)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.PROTECT)
    open_for_entries = models.DateTimeField(null=True)
    entries_close = models.DateTimeField(null=True)
    open_for_judging = models.DateTimeField(null=True)
    judging_closes =  models.DateTimeField(null=True)
    judge_awards = models.BooleanField(default=True)
    members_vote = models.BooleanField(default=True)

main/templates/main/includes/comp_dir_buttons.html
{% if 'End of Year' in competition.type.type and "Mono Prints" in competition.type.type %}
    <a class="btn btn-primary float-right mt-1" href="{% url 'end_of_year_entry_mono_prints' %}">Select Entries</a>
    <a class="btn btn-primary float-right mt-1" href="{% url 'end_of_year_entry_mono_labels' %}">Labels</a>
{% elif 'End of Year' in competition.type.type and "Colour Prints" in competition.type.type %}
    <a class="btn btn-primary float-right mt-1" href="{% url 'end_of_year_entry_colour_prints' %}">Select Entries</a>
    <a class="btn btn-primary float-right mt-1" href="{% url 'end_of_year_entry_colour_labels' %}">Labels</a>
{% endif %}

{% if competition.images.all %}<a class="btn btn-primary mt-1" href="{% url 'list_entries' competition.id %}">List of Entries</a>{% endif %}
{% if competition.images.all %}<a class="btn btn-primary mt-1" href="{% url 'view_entries' competition.id %}">View Entries</a>{% endif %}
{% if competition.images.all %}<a class="btn btn-primary mt-1" href="{% url 'create_zip' competition.id %}">Download Zip</a>{% endif %}
<a class="btn btn-primary mt-1" href="{% url 'competition_add_images' competition.id %}">Add Images</a>
{% if competition.images.all %}<a class="btn btn-primary mt-1" href="{% url 'edit_judge_awards' competition.id %}">Edit Judge Awards</a>{% endif %}
{% if competition.images.all %}<a class="btn btn-primary mt-1" href="{% url 'edit_member_awards' competition.id %}">Edit Member Awards</a>{% endif %}

main/templates/main/includes/event_card.html
{% load static %}
<div class="card event-card">
    <a href="{% url 'event' event.id %}" class="card-link">
    <div class="image-container">
        {% if event.image.photo %}
        <img src="{{ event.image.photo.url }}" class="card-img-top" alt="{{ event.image.title }}">
        {% elif event.file and 'jpg' in event.extension %}
            <img class="img-thumbnail" src="{{ event.file.url }}" class="card-img-top" alt="Image related to event">
        {% elif event.file and 'pdf' in event.extension %}
            <div id="pdf-viewer" class="embed-responsive"></div>
        {% else %}
            {% if event.competition_set.all %}
            {% for comp in event.competition_set.all %}
            {% if comp.type.type == 'Open Colour Digital' %}
                <img src="{% get_media_prefix %}{{ 'photos/Set_World of Colours_Stan Bendkowski.jpg' }}" class="card-img-top" alt="{{ event.image.title }}">
            {% elif comp.type.type == 'Open Mono Digital' %}
                <img src="{% get_media_prefix %}{{ 'photos/m_WAC_Jocelyn Manning_Checking Out.jpg' }}" class="card-img-top" alt="{{ event.image.title }}">
            {% endif %}
            {% endfor %}
            {% endif %}
        {% endif %}
        <div class="start-date">{{ event.starts|date:"j" }}</div>
        <div class="event-name-overlay">
            {{ event.name }}
        </div>
    </div>
    {% if event.description %}
    <div class="card-body">
        <p class="card-text">{{ event.description|linebreaks }}</p>
    </div>
    {% endif %}
    {% if event.competition_set.all %}
    <ul class="list-group list-group-flush">
        {% for comp in event.competition_set.all %}
        {% if comp.type.type == 'Open Colour Digital' %}
            <li class="list-group-item">{{ comp.subject }}</li>
        {% elif comp.type.type == 'Open Mono Digital' %}
            <li class="list-group-item">{{ comp.subject }}</li>
        {% elif comp.type.type == "Set Digital" %}
            <li class="list-group-item">Set Subject: {{ comp.subject }}</li>
            {% if comp.open_for_entries|date:"Y-m-d H:i" > right_now  %}
                <li class="list-group-item">Digital Entries Open {{ comp.open_for_entries|date:"M jS" }} at {{ comp.open_for_entries|date:"g:i A" }}</li>
            {% elif comp.entries_close|date:"Y-m-d H:i" > right_now  %}
                <li class="list-group-item">Digital Entries Close {{ comp.entries_close|date:"jS" }} at {{ comp.entries_close|date:"g:i A" }}</li>
            {% elif comp.open_for_juding|date:"Y-m-d H:i" > right_now and comp.members_vote %}
                <li class="list-group-item">Voting Starts {{ comp.open_for_judging|date:"jS" }} at {{ comp.open_for_judging|date:"g:i A" }}</li>
            {% elif comp.juding_closes|date:"Y-m-d H:i" > right_now and comp.members_vote %}
                <li class="list-group-item">Voting Closes {{ comp.judging_closes|date:"jS" }} at {{ comp.judging_closes|date:"g:i A" }}</li>
            {% endif %}
        {% endif %}
        {% endfor %}
      </ul>
    {% endif %}
</a>
</div>

main/templates/main/includes/event_card_hidden.html
{% load static %}
<div class="card event-card">
    <a href="{% url 'event' event.id %}" class="card-link">
    <div class="image-container">
        {% if event.image.photo %}
        <img src="{{ event.image.photo.url }}" class="card-img-top" alt="{{ event.image.title }}">
        {% elif event.file and 'jpg' in event.extension %}
            <img class="img-thumbnail" src="{{ event.file.url }}" class="card-img-top" alt="Image related to event">
        {% elif event.file and 'pdf' in event.extension %}
            <div id="pdf-viewer" class="embed-responsive"></div>
        {% else %}
            {% if event.competition_set.all %}
            {% for comp in event.competition_set.all %}
            {% if comp.type.type == 'Open Colour Digital' %}
                <img src="{% get_media_prefix %}{{ 'photos/Set_World of Colours_Stan Bendkowski.jpg' }}" class="card-img-top" alt="{{ event.image.title }}">
            {% elif comp.type.type == 'Open Mono Digital' %}
                <img src="{% get_media_prefix %}{{ 'photos/m_WAC_Jocelyn Manning_Checking Out.jpg' }}" class="card-img-top" alt="{{ event.image.title }}">
            {% endif %}
            {% endfor %}
            {% endif %}
        {% endif %}
        <div class="start-date">{{ event.starts|date:"j" }}</div>
        <div class="event-name-overlay">
            ---HIDDEN---{{ event.name }}---HIDDEN---
        </div>
    </div>
    {% if event.description %}
    <div class="card-body">
        <p class="card-text">{{ event.description|linebreaks|truncatewords:50 }}</p>
    </div>
    {% endif %}
    {% if event.competition_set.all %}
    <ul class="list-group list-group-flush">
        {% for comp in event.competition_set.all %}
        {% if comp.type.type == 'Open Colour Digital' %}
            <li class="list-group-item">{{ comp.subject }}</li>
        {% elif comp.type.type == 'Open Mono Digital' %}
            <li class="list-group-item">{{ comp.subject }}</li>
        {% elif comp.type.type == "Set Digital" %}
            <li class="list-group-item">Set Subject: {{ comp.subject }}</li>
            {% if comp.open_for_entries|date:"Y-m-d H:i" > right_now  %}
                <li class="list-group-item">Digital Entries Open {{ comp.open_for_entries|date:"M jS" }} at {{ comp.open_for_entries|date:"g:i A" }}</li>
            {% elif comp.entries_close|date:"Y-m-d H:i" > right_now  %}
                <li class="list-group-item">Digital Entries Close {{ comp.entries_close|date:"jS" }} at {{ comp.entries_close|date:"g:i A" }}</li>
            {% elif comp.open_for_juding|date:"Y-m-d H:i" > right_now and comp.members_vote %}
                <li class="list-group-item">Voting Starts {{ comp.open_for_judging|date:"jS" }} at {{ comp.open_for_judging|date:"g:i A" }}</li>
            {% elif comp.juding_closes|date:"Y-m-d H:i" > right_now and comp.members_vote %}
                <li class="list-group-item">Voting Closes {{ comp.judging_closes|date:"jS" }} at {{ comp.judging_closes|date:"g:i A" }}</li>
            {% endif %}
        {% endif %}
        {% endfor %}
      </ul>
    {% endif %}
</a>
</div>

main/templates/main/includes/gallery.html
{% if gallery.private == True %}
<h3>{{ gallery.name }}</h3>
{% else %}
<h3>Images from {{ gallery.name }}</h3>
{% endif %}
{% comment %} if the gallery has any images uploaded {% endcomment %}
<ul class="image-gallery">
    {% for image in images %}
    {% if image.photo %}
        {% include "main/includes/gallery_items.html" %}
    {% endif %}
    {% endfor %}
</ul>

main/templates/main/includes/gallery_items.html
<li>
  {% if image.photo %}
    <img loading="lazy" src="{{ image.photo.url }}" alt="{{ image.title }}">
  {% else %}
    <img src="" alt="{{ image.title }}"> <br/><i>Click to upload image</i>
  {% endif %}
  <div class="overlay">
    <div>{{ image.title }}</div>
    <div>by {{ image.author }}</div>
    {% for award in image.award_set.all %}
    <div>{{ award.type.name }} {{ award.type.awarded_by.awarded_by }}</div>
    {% if forloop.last %}
      {% if 'Open' in award.competition.type.type %}
        <div>in {{ award.competition.type }}</div>
      {% else %}
        <div>in {{ award.competition.type }} - {{ award.competition.subject }}</div>
      {% endif %}
    {% endif %}
    {% endfor %}
  </div>
  <!-- Link to trigger the modal -->
  {% if image.photo %}
  <a class="divLink" href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{ image.id }}"></a>
  {% else %}
  <a class="divLink" href="{% url 'upload_photo' image.id %}"></a>
  {% endif %}
</li>
<!-- Modal for the image -->
{% if image.photo %}
<div class="modal fade " id="imageModal{{ image.id }}" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content modal-content-centrered">
            <div class="wacc-modal-body">
                <img src="{{ image.photo.url }}" alt="{{ image.title }}">
            </div>
        </div>
    </div>
</div>
{% endif %}

main/templates/main/includes/gallery_items_blind.html
<li>
  <img src="{{ image.photo.url }}" alt="{{ image.title }}">
  <div class="overlay">
    <div><h1>{{ forloop.counter }}</h1></div>
  </div>
  <!-- Link to trigger the modal -->
  <a class="divLink" href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{ image.id }}" 
  {% if "President" in user.person.position.first.position or "Competition" in user.person.position.first.position or "Webmaster" in user.person.position.first.position and voting == False%}
    title="{{image.title}} &#013; {{image.author}} &#013; {{ image.dimensions }} &#013; {{ image.capture_date }}"{% endif%}></a> 
</li>
<!-- Modal for the image -->
<div class="modal fade" id="imageModal{{ image.id }}" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content modal-content-centered">
          <div class="wacc-modal-body-voting">
              <img src="{{ image.photo.url }}" alt="Image Missing, please contact the webmaster">
              {% with current_pic=forloop.counter %}
              <div class="m-1">
                  <div>
                      {% if current_pic > 1 %}
                            {% with prev=forloop.counter|add:"-1" %}
                              {% with prev_image_id=image_index|slice:prev|last %}
                                  <a id="prev-{{ image.id }}" class="btn btn-outline-primary" href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{ prev_image_id }}">Previous</a>
                              {% endwith %}
                          {% endwith %}
                      {% endif %}
                      {% for image in images %}
                          {% if forloop.counter == current_pic %}
                              <a class="btn btn-primary" href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{ image.id }}">{{ forloop.counter }}</a>
                          {% else %}
                              <a class="btn" href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{ image.id }}">{{ forloop.counter }}</a>
                          {% endif %}
                      {% endfor %}
                      {% if current_pic < images|length %}
                          {% with next=forloop.counter|add:"1" %}
                              {% with next_image_id=image_index|slice:next|last %}
                                  <a id="next-{{ image.id }}" class="btn btn-outline-primary" href="#" data-bs-toggle="modal" data-bs-target="#imageModal{{ next_image_id }}">Next</a>
                              {% endwith %}
                          {% endwith %}
                      {% endif %}
                  </div>
              </div>
              {% endwith %}
          </div>
      </div>
  </div>
</div>